first commit
ViktoriaShamuradova/MJS-School pull request #1
Opened 2021-01-20 06:37 UTC by ViktoriaShamuradova

2021-01-21 18:00 UTC, mvladmoss commented on model/src/main/java/com/epam/esm/dto/CertificateDTO.java
> +    private int id;
Why int? Potentially you can have a lot of certificates, please replace with Long

2021-01-21 18:00 UTC, mvladmoss commented on model/src/main/java/com/epam/esm/dto/CertificateDTO.java
> +    private LocalDateTime createDate;
I suggest using Instant class, it will handle time correctly regardless of client timeZone.

2021-01-21 18:00 UTC, mvladmoss commented on service/src/main/java/com/epam/esm/CertificateService.java
> +    @Transactional
Why did you place here this annotation? Why you didn't place it also for other methods?

2021-01-21 18:00 UTC, mvladmoss commented on service/src/main/java/com/epam/esm/impl/CertificateServiceImpl.java
> +    public List<CertificateDTO> getAllCertificates() {
Please use @Transactiona(readOnly = true) annotation for read operations too.
![image](https://user-images.githubusercontent.com/32880986/104951425-84728000-59d3-11eb-9a99-709ae0991f0c.png)
https://stackoverflow.com/questions/44984781/what-are-advantages-of-using-transactionalreadonly-true

2021-01-21 18:00 UTC, mvladmoss commented on web/src/main/java/com/epam/esm/CertificateController.java
> +        if (certificate == null) {
This business logic check should be moved to the service

2021-01-21 18:00 UTC, mvladmoss commented on web/src/main/java/com/epam/esm/CertificateController.java
> +    public List<CertificateDTO> showCertificateByPartOfDescription(@RequestBody CertificateDTO certificateDTO) {
What is the reason to pass full certificateDto if you only need a name and description? Also this is a read operation, why did you decide to choose post method?

2021-01-21 18:00 UTC, mvladmoss commented on web/src/main/java/com/epam/esm/config/DBConfig.java
> +    public DataSource dataSource() {
What does configuration which is related to the database do in WebConfig?

2021-01-21 18:00 UTC, mvladmoss commented on web/src/main/java/com/epam/esm/config/DBConfig.java
> +public class DBConfig implements WebMvcConfigurer {
Each of your modules(except domain) should include its own Configuration class. Each of these configurations has to make component scan only for this module and customize appropriate beans. In order to include configuration from one module to another one, use annotation @import.

2021-01-22 10:05 UTC, nikskonda commented on persistence/src/main/java/com/epam/esm/impl/CertificateDAOImpl.java
> +            ps.setString(1, certificate.getName());
It prepare to use NamedParameterStatement.
https://www.infoworld.com/article/2077706/named-parameters-for-preparedstatement.html

2021-01-22 10:05 UTC, nikskonda commented on service/src/main/java/com/epam/esm/TagService.java
> +    TagDTO createTag(TagDTO tagDTO);
I think its better to use "create", "get", ... method name, because its obvious that it will be tag from the name of interface. And it will be nice to move similar methods to CRUD generic interface.

2021-01-22 10:05 UTC, nikskonda commented on service/src/main/java/com/epam/esm/impl/TagServiceImpl.java
> +        return null;
Please use Optional.

2021-01-22 10:05 UTC, nikskonda commented on web/src/main/java/com/epam/esm/exceptionHandling/IncorrectData.java
> +public class IncorrectData {
![image](https://user-images.githubusercontent.com/24493000/105476106-46b27780-5cb1-11eb-9b55-d35f80257555.png)

2021-01-22 10:05 UTC, nikskonda commented on web/src/main/java/com/epam/esm/config/DBConfig.java
> +        dataSource.setPassword("student");
Please use values from db.propeties.

2021-01-22 10:36 UTC, nikskonda commented on model/src/main/java/com/epam/esm/entity/Certificate.java
> +    private Integer price;
I think its better to use BigDecimal for price.

2021-01-24 20:44 UTC, maryia-haladko requested changes
I don't see any javadoc and the requirement 

> 9. Several configurations should be implemented (at least two - dev and prod).

 is not implemented as well

2021-01-24 20:44 UTC, justmahito commented on build.gradle
> +subprojects {
it's good to have **sourceCompatibility** property

2021-01-24 20:44 UTC, justmahito commented on model/src/main/java/com/epam/esm/dto/CertificateDTO.java
> +    @DecimalMin(value = "0", message = "Enter certificate price")
does it make sense to have min value = 0?

2021-01-24 20:44 UTC, justmahito commented on model/src/main/java/com/epam/esm/dto/CertificateDTO.java
> +    @Size(min = 3, max = 20, message = "The certificate name could be between 3 and 20 symbols")
use **should**

2021-01-24 20:44 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/CertificateDAO.java
> +    void update(long id, Certificate certificate);
why do you need to pass id separately?

2021-01-24 20:44 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/CertificateDAO.java
> +    List<Certificate> allCertificates();
remove **certificate** part from methods names - it's redundant in **CertificateDAO**, use **find** prefix

2021-01-24 20:44 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/CertificateDAO.java
> +    List<Certificate> getCertificatesByPartOfNameOrDescription(String name, String description);
the meaning of the task was to pass single search term and search in both name and description

2021-01-24 20:44 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/TagDAO.java
> +    List<Tag> findAllTagList();
remove **tag** part from methods names - it's redundant in **TagDAO**

2021-01-24 20:44 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/impl/CertificateDAOImpl.java
> +        jdbcTemplate.update(SQL_QUERY_UPDATE_CERTIFICATE, certificate.getName(),
check NamedParameterJdbcTemplate

2021-01-24 20:44 UTC, maryia-haladko commented on persistence/src/main/java/com/epam/esm/persistence/impl/CertificateDAOImpl.java
> +        return jdbcTemplate.query(FIRST_PART_OF_SQL_QUERY_READ_CERTIFICATES_BY_PART_OF_NAME_AND_DESCRIPTION + name +
reimplement this method to search by one term in both fields and don't forget to **always** use prepared statements! there is no difference if it's a **like** operator or any other

2021-01-24 20:44 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        Certificate certificateFromDb = certificateDAO.certificateById(certificateId);
the certificate may not be found

2021-01-24 20:44 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +                for (TagDTO tagDTO : certificateDTO.getTagList()) {
what if the list of tags is empty?

2021-01-24 20:44 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +            certificateFromDb.setUpdateLastDate(Instant.now());
what if no fields were updated?

2021-01-24 20:44 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +        if (tag != null) {
why do you need to check for null if you anyway return null in the end? and also check comment regarding Optional

2021-01-24 20:44 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/entitydtomapper/impl/TagDTOMapperImpl.java
> +public class TagDTOMapperImpl implements TagDtoMapper {
i don't see a lot of sense in using both DTOs here, they only bring more complexity

2021-01-24 20:44 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +            System.out.println("execute");
use logger for debug messages as well

2021-01-24 20:44 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +    @Autowired
check how you can decrease complexity to avoid this cyclic dependencies

2021-01-24 20:44 UTC, maryia-haladko commented on service/src/test/java/com/epam/esm/persistence/impl/CertificateServiceImplTest.java
> +//    @Mock
why the tests are commented out?

2021-01-24 20:44 UTC, maryia-haladko commented on web/src/main/java/com/epam/esm/web/TagController.java
> +        return "Tag with id= " + tagId + " was deleted";
build proper response with http code

2021-01-24 20:44 UTC, maryia-haladko commented on web/src/main/java/com/epam/esm/web/TagController.java
> +        if (tagDTO == null) {
move all such checks to service

2021-01-24 20:44 UTC, maryia-haladko commented on web/src/main/java/com/epam/esm/web/exceptionHandling/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(data, HttpStatus.I_AM_A_TEAPOT);
use proper http code

2021-01-24 20:44 UTC, maryia-haladko commented on web/src/main/resources/db.propeties
> +db.driver= org.gjt.mm.mysql.Driver
move it to persistence module and use

2021-01-24 20:44 UTC, maryia-haladko commented on web/src/main/java/com/epam/esm/web/exceptionHandling/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(data, HttpStatus.BAD_REQUEST);
i think better user 500 here

2021-01-25 06:20 UTC, volha-bibik commented on persistence/src/main/java/com/epam/esm/persistence/impl/CertificateDAOImpl.java
> +    private static final String SQL_QUERY_INSERT_CERTIFICATE = "insert into module2_certificates_tags.certificates " +
it's better to use one case for all statements: usually it's upper case for all sql commands

2021-01-25 06:20 UTC, volha-bibik commented on persistence/src/main/java/com/epam/esm/persistence/impl/TagDAOImpl.java
> +    private static final String SQL_QUERY_READ_TAG_LIST = "Select * from module2_certificates_tags.tags;";
it's better to use one case for all statements: usually it's upper case for all sql commands

2021-01-25 10:10 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +        if (tag != null) {
reminder: return Optional from DAO -> use Optional.orElseThrow in Service

2021-01-25 10:10 UTC, maryia-haladko commented on persistence/src/main/java/com/epam/esm/persistence/CertificateDAO.java
> +    void update(long id, Certificate certificate);
reminder: read(response)/write(request) DTOs

2021-01-25 10:10 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/entitydtomapper/impl/TagDTOMapperImpl.java
> +public class TagDTOMapperImpl implements TagDtoMapper {
reminder: read(response)/write(request) DTOs

2021-01-25 10:10 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +                for (TagDTO tagDTO : certificateDTO.getTagList()) {
reminder: proper tags update

2021-01-26 20:03 UTC, maryia-haladko requested changes

2021-01-26 20:03 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/CertificateDAO.java
> +    void update(CertificateDTO certificateDTO);
be consistent, pass Certificate

2021-01-26 20:03 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/impl/CertificateDAOImpl.java
> +//don't work
try to make it with the usual like statement

2021-01-26 20:03 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/impl/CertificateDAOImpl.java
> +        StringBuilder queryStart = new StringBuilder("UPDATE certificates SET ");
add the string to constants

2021-01-26 20:03 UTC, justmahito commented on persistence/src/main/java/com/epam/esm/persistence/impl/CertificateDAOImpl.java
> +            queryStart.append("name= :name,");
better reimplement it in more generic way to avoid issues with spaces and commas

2021-01-26 20:03 UTC, justmahito commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        find(id);
we don't need to call find as you can handle number of affected raws in delete

2021-01-26 20:03 UTC, justmahito commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        if (certificateDTO.getTagList() != null) {
no comparison with existing tags list: what if tags list was changed and we need to delete the old references

2021-01-26 20:03 UTC, justmahito commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +    private boolean isFieldsChanged(CertificateDTO certificateDTO) {
duration?

2021-01-26 20:03 UTC, maryia-haladko commented on service/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +        if (tagDAO.find(tagDTO.getName()).isPresent())
use brackets

2021-02-10 07:07 UTC, merged